package ch_6;

public class Chapter6 {
}

/*
CLASS Modifiers
1) public - accessible from anywhere
2) default (no modifier) - accessible only within the same package
3) final - cannot be subclassed
4) abstract - cannot be instantiated, can have abstract methods that must be implemented by subclasses
5) static - nested classes can be static, but top-level classes cannot be static
 */
class Interview{
    String companyName;
    static int age=9;
    protected int noticePeriod =15;
}

class Tcs extends Interview{
    int noticePeriod=90;
    String location="Chennai";
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
        age=1;
        System.out.println(super.noticePeriod); //15
        System.out.println(noticePeriod); //90  current class variable
        System.out.println(this.noticePeriod); //90 current class variable
        System.out.println(this.location);
       // System.out.println(super.location); // doest compile
    }
    public static void main(String[] args) {
        Tcs tcs = new Tcs();
        tcs.setCompanyName("TCS");
        System.out.println("Company Name: " + tcs.companyName);
        System.out.println("Age: " + Tcs.age); //1
        System.out.println("Age: " + Interview.age); //1
        System.out.println("TCS Notice Period: " + tcs.noticePeriod);
    }
}


/*
CONSTRUCTOR
Name should match class name
no return type
var is not allowed in constructor parameters

 */
class ConstructorExample{
    String name;
    int age;

    // Default constructor

    private ConstructorExample() {
        this.name = "Default Name";
        this.age = 0;
    }
    //var not allowed in constructor parameters
//    public ConstructorExample(var age){
//        this.name="Default Name";
//        this.age=age;
//    }

    // Parameterized constructor
    public ConstructorExample(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public static void main(String[] args) {
        ConstructorExample example1 = new ConstructorExample();
        System.out.println("Example 1 - Name: " + example1.name + ", Age: " + example1.age);

        ConstructorExample example2 = new ConstructorExample("Alice", 30);
        System.out.println("Example 2 - Name: " + example2.name + ", Age: " + example2.age);
    }
}
class ConstructorExample2{
    public static void main(String[] args) {
        //ConstructorExample example1 = new ConstructorExample(); // Cannot access private constructor
        ConstructorExample example2 = new ConstructorExample("Bob", 25); // Can access public constructor
    }
}

//No arg default cons not generated here
//default constructors are auto generated by compiler, only if no cons is defined by the programmer
//default constructor = no arg constructor
class Arun{
    int age;
    public Arun(int age){
        this.age=age;
    }
}
class Sample{
    public static void main(String[] args) {
        //Arun arun1 = new Arun(); //compile error - no default constructor
        Arun arun = new Arun(30);
        System.out.println(arun.age); //30
    }
}


//this () - calling another constructor in the same class
//this() must be the first statement in the constructor
class Sample2{
    String name;
    int age;
    public Sample2(int age){
        this.age=age;
        this.name="Default Name";
    }
    public Sample2(String name, int age){
       // System.out.println("first line"); -- adding this line will cause compile error because this() must be the first statement
        this(age); // calling the constructor with int parameter
       // Sample2(age); // not possible
        this.name=name;
    }
    public static void main(String[] args) {
        Sample2 sample1 = new Sample2(25);
        System.out.println("Name: " + sample1.name + ", Age: " + sample1.age);
        Sample2 sample = new Sample2("Alice", 30);
        System.out.println("Name: " + sample.name + ", Age: " + sample.age);

    }
}

//super() - calling parent class constructor
// super() must be the first statement in the constructor
class Parent{
    String name;
    public Parent(String name){
        this.name=name;
    }
}
class Child extends Parent{
    int age;
    public Child(String name){
        //System.out.println("hi"); //doesnt compile
        super(name); // calling parent constructor
        this.age=12;
    }
    public Child(){
        this("arun");
    }
    public static void main(String[] args) {
        Child child = new Child();
        System.out.println("Name: " + child.name + ", Age: " + child.age);
    }
}

class Animal {
    public  int age;
    public String name;
    public Animal(int age, String name) {
        super(); //repeated call is allowed
        this.age = age;
        this.name = name;
    }
    public Animal(int age) {
        super();
        this.age = age;
        this.name = null;
    }
}
class Gorilla extends Animal {
    public Gorilla(int age) {
        super(age,"Gorilla"); // Calls the first Animal constructor
    }
    public Gorilla() {
        super(5); // Calls the second Animal constructor
    }
}
class GorillaTest {
    public static void main(String[] args) {
        Gorilla gorilla1 = new Gorilla(10);
        Gorilla gorilla2 = new Gorilla();
        System.out.println("Gorilla 1 - Age: " + gorilla1.age + ", Name: " + gorilla1.name); // Age: 10, Name: Gorilla
        System.out.println("Gorilla 2 - Age: " + gorilla2.age + ", Name: " + gorilla2.name); // Age: 5, Name: null
    }
}

class Sample4 {
    String name;

    public Sample4(String name) {
        this.name = name;
    }
}
class Hey extends Sample4{
    public Hey(String name) {
        super(name); //must when parent has param cons
    }
    public static void main(String[] args) {
        Hey hey = new Hey("Hello");
        System.out.println(hey.name); // Hello
    }
}